[tool.poetry]
name = "gapminder_challenge"
version = "1.0.0"
description = "Package for Data Visualization"
authors = ["DSCI532_Group12"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
